//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------



//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------


namespace customer_integration.Infrastructure.CRM.Models
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum dev_CustomerState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("dev_customer")]
	public partial class dev_Customer : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string dev_budget = "dev_budget";
			public const string dev_budget_Base = "dev_budget_base";
			public const string dev_CustomerId = "dev_customerid";
			public const string Id = "dev_customerid";
			public const string dev_customertype = "dev_customertype";
			public const string dev_name = "dev_name";
			public const string dev_preferredcity = "dev_preferredcity";
			public const string ExchangeRate = "exchangerate";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string lk_dev_customer_createdby = "lk_dev_customer_createdby";
			public const string lk_dev_customer_createdonbehalfby = "lk_dev_customer_createdonbehalfby";
			public const string lk_dev_customer_modifiedby = "lk_dev_customer_modifiedby";
			public const string lk_dev_customer_modifiedonbehalfby = "lk_dev_customer_modifiedonbehalfby";
			public const string user_dev_customer = "user_dev_customer";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public dev_Customer() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "dev_customer";
		
		public const string EntitySchemaName = "dev_Customer";
		
		public const string PrimaryIdAttribute = "dev_customerid";
		
		public const string PrimaryNameAttribute = "dev_name";
		
		public const string EntityLogicalCollectionName = "dev_customers";
		
		public const string EntitySetName = "dev_customers";
		
		public const int EntityTypeCode = 10684;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator użytkownika, który utworzył rekord.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Data i godzina utworzenia rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator użytkownika delegowanego, który utworzył rekord.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dev_budget")]
		public Microsoft.Xrm.Sdk.Money dev_budget
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("dev_budget");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_budget");
				this.SetAttributeValue("dev_budget", value);
				this.OnPropertyChanged("dev_budget");
			}
		}
		
		/// <summary>
		/// Wartość pola Budget w walucie podstawowej.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dev_budget_base")]
		public Microsoft.Xrm.Sdk.Money dev_budget_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("dev_budget_base");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator wystąpień encji
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dev_customerid")]
		public System.Nullable<System.Guid> dev_CustomerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("dev_customerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_CustomerId");
				this.SetAttributeValue("dev_customerid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("dev_CustomerId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dev_customerid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.dev_CustomerId = value;
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dev_customertype")]
		public virtual dev_Customer_dev_customertype? dev_customertype
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((dev_Customer_dev_customertype?)(EntityOptionSetEnum.GetEnum(this, "dev_customertype")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_customertype");
				this.SetAttributeValue("dev_customertype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("dev_customertype");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dev_name")]
		public string dev_name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dev_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_name");
				this.SetAttributeValue("dev_name", value);
				this.OnPropertyChanged("dev_name");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dev_preferredcity")]
		public string dev_preferredcity
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dev_preferredcity");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_preferredcity");
				this.SetAttributeValue("dev_preferredcity", value);
				this.OnPropertyChanged("dev_preferredcity");
			}
		}
		
		/// <summary>
		/// Kurs wymiany waluty skojarzonej z encją w odniesieniu do waluty podstawowej.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Numer sekwencyjny operacji importu, w wyniku której został utworzony ten rekord.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator użytkownika, który zmodyfikował rekord.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Data i godzina modyfikacji rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator użytkownika delegowanego, który zmodyfikował rekord.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Data i godzina migracji rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator jednostki biznesowej, która jest właścicielem rekordu
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator zespołu, który jest właścicielem rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator użytkownika, który jest właścicielem rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Stan elementu/elementów Customer
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<customer_integration.Infrastructure.CRM.Models.dev_CustomerState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((customer_integration.Infrastructure.CRM.Models.dev_CustomerState)(System.Enum.ToObject(typeof(customer_integration.Infrastructure.CRM.Models.dev_CustomerState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Przyczyna stanu elementu/elementów Customer
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual dev_Customer_StatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((dev_Customer_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// Tylko do użytku wewnętrznego.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator waluty skojarzonej z encją.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// Kod strefy czasowej używanej podczas tworzenia rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Numer wersji
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N dev_appointment_customer_dev_customer
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dev_appointment_customer_dev_customer")]
		public System.Collections.Generic.IEnumerable<customer_integration.Infrastructure.CRM.Models.dev_Appointment> dev_appointment_customer_dev_customer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<customer_integration.Infrastructure.CRM.Models.dev_Appointment>("dev_appointment_customer_dev_customer", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_appointment_customer_dev_customer");
				this.SetRelatedEntities<customer_integration.Infrastructure.CRM.Models.dev_Appointment>("dev_appointment_customer_dev_customer", null, value);
				this.OnPropertyChanged("dev_appointment_customer_dev_customer");
			}
		}
		
		/// <summary>
		/// 1:N dev_case_customer_dev_customer
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dev_case_customer_dev_customer")]
		public System.Collections.Generic.IEnumerable<customer_integration.Infrastructure.CRM.Models.dev_Case> dev_case_customer_dev_customer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<customer_integration.Infrastructure.CRM.Models.dev_Case>("dev_case_customer_dev_customer", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_case_customer_dev_customer");
				this.SetRelatedEntities<customer_integration.Infrastructure.CRM.Models.dev_Case>("dev_case_customer_dev_customer", null, value);
				this.OnPropertyChanged("dev_case_customer_dev_customer");
			}
		}
		
		/// <summary>
		/// 1:N dev_Customer_appointment_dev_Appointment
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dev_Customer_appointment_dev_Appointment")]
		public System.Collections.Generic.IEnumerable<customer_integration.Infrastructure.CRM.Models.dev_Appointment> dev_Customer_appointment_dev_Appointment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<customer_integration.Infrastructure.CRM.Models.dev_Appointment>("dev_Customer_appointment_dev_Appointment", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_Customer_appointment_dev_Appointment");
				this.SetRelatedEntities<customer_integration.Infrastructure.CRM.Models.dev_Appointment>("dev_Customer_appointment_dev_Appointment", null, value);
				this.OnPropertyChanged("dev_Customer_appointment_dev_Appointment");
			}
		}
		
		/// <summary>
		/// 1:N dev_Customer_case_dev_Case
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dev_Customer_case_dev_Case")]
		public System.Collections.Generic.IEnumerable<customer_integration.Infrastructure.CRM.Models.dev_Case> dev_Customer_case_dev_Case
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<customer_integration.Infrastructure.CRM.Models.dev_Case>("dev_Customer_case_dev_Case", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_Customer_case_dev_Case");
				this.SetRelatedEntities<customer_integration.Infrastructure.CRM.Models.dev_Case>("dev_Customer_case_dev_Case", null, value);
				this.OnPropertyChanged("dev_Customer_case_dev_Case");
			}
		}
		
		/// <summary>
		/// 1:N dev_lead2_customer_dev_customer
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dev_lead2_customer_dev_customer")]
		public System.Collections.Generic.IEnumerable<customer_integration.Infrastructure.CRM.Models.dev_Lead2> dev_lead2_customer_dev_customer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<customer_integration.Infrastructure.CRM.Models.dev_Lead2>("dev_lead2_customer_dev_customer", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_lead2_customer_dev_customer");
				this.SetRelatedEntities<customer_integration.Infrastructure.CRM.Models.dev_Lead2>("dev_lead2_customer_dev_customer", null, value);
				this.OnPropertyChanged("dev_lead2_customer_dev_customer");
			}
		}
		
		/// <summary>
		/// N:1 lk_dev_customer_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_dev_customer_createdby")]
		public customer_integration.Infrastructure.CRM.Models.SystemUser lk_dev_customer_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<customer_integration.Infrastructure.CRM.Models.SystemUser>("lk_dev_customer_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_dev_customer_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_dev_customer_createdonbehalfby")]
		public customer_integration.Infrastructure.CRM.Models.SystemUser lk_dev_customer_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<customer_integration.Infrastructure.CRM.Models.SystemUser>("lk_dev_customer_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_dev_customer_createdonbehalfby");
				this.SetRelatedEntity<customer_integration.Infrastructure.CRM.Models.SystemUser>("lk_dev_customer_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_dev_customer_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_dev_customer_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_dev_customer_modifiedby")]
		public customer_integration.Infrastructure.CRM.Models.SystemUser lk_dev_customer_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<customer_integration.Infrastructure.CRM.Models.SystemUser>("lk_dev_customer_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_dev_customer_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_dev_customer_modifiedonbehalfby")]
		public customer_integration.Infrastructure.CRM.Models.SystemUser lk_dev_customer_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<customer_integration.Infrastructure.CRM.Models.SystemUser>("lk_dev_customer_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_dev_customer_modifiedonbehalfby");
				this.SetRelatedEntity<customer_integration.Infrastructure.CRM.Models.SystemUser>("lk_dev_customer_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_dev_customer_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 user_dev_customer
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_dev_customer")]
		public customer_integration.Infrastructure.CRM.Models.SystemUser user_dev_customer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<customer_integration.Infrastructure.CRM.Models.SystemUser>("user_dev_customer", null);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public dev_Customer(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["dev_customerid"] = base.Id;
                        break;
                    case "dev_customerid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}
