//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------



//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------


namespace customer_integration.Infrastructure.CRM.Models
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum dev_CaseState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("dev_case")]
	public partial class dev_Case : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string dev_apartment = "dev_apartment";
			public const string dev_case = "dev_case";
			public const string dev_CaseId = "dev_caseid";
			public const string Id = "dev_caseid";
			public const string dev_cases = "dev_cases";
			public const string dev_customer = "dev_customer";
			public const string dev_description = "dev_description";
			public const string dev_priority = "dev_priority";
			public const string dev_title = "dev_title";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string dev_Apartment_cases_dev_Case = "dev_Apartment_cases_dev_Case";
			public const string dev_case_apartment_dev_apartment = "dev_case_apartment_dev_apartment";
			public const string dev_case_customer_dev_customer = "dev_case_customer_dev_customer";
			public const string dev_Customer_case_dev_Case = "dev_Customer_case_dev_Case";
			public const string lk_dev_case_createdby = "lk_dev_case_createdby";
			public const string lk_dev_case_createdonbehalfby = "lk_dev_case_createdonbehalfby";
			public const string lk_dev_case_modifiedby = "lk_dev_case_modifiedby";
			public const string lk_dev_case_modifiedonbehalfby = "lk_dev_case_modifiedonbehalfby";
			public const string user_dev_case = "user_dev_case";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public dev_Case() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "dev_case";
		
		public const string EntitySchemaName = "dev_Case";
		
		public const string PrimaryIdAttribute = "dev_caseid";
		
		public const string PrimaryNameAttribute = "dev_title";
		
		public const string EntityLogicalCollectionName = "dev_cases";
		
		public const string EntitySetName = "dev_cases";
		
		public const int EntityTypeCode = 10683;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator użytkownika, który utworzył rekord.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Data i godzina utworzenia rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator użytkownika delegowanego, który utworzył rekord.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dev_apartment")]
		public Microsoft.Xrm.Sdk.EntityReference dev_apartment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dev_apartment");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_apartment");
				this.SetAttributeValue("dev_apartment", value);
				this.OnPropertyChanged("dev_apartment");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dev_case")]
		public Microsoft.Xrm.Sdk.EntityReference dev_case
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dev_case");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_case");
				this.SetAttributeValue("dev_case", value);
				this.OnPropertyChanged("dev_case");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator wystąpień encji
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dev_caseid")]
		public System.Nullable<System.Guid> dev_CaseId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("dev_caseid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_CaseId");
				this.SetAttributeValue("dev_caseid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("dev_CaseId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dev_caseid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.dev_CaseId = value;
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dev_cases")]
		public Microsoft.Xrm.Sdk.EntityReference dev_cases
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dev_cases");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_cases");
				this.SetAttributeValue("dev_cases", value);
				this.OnPropertyChanged("dev_cases");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dev_customer")]
		public Microsoft.Xrm.Sdk.EntityReference dev_customer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dev_customer");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_customer");
				this.SetAttributeValue("dev_customer", value);
				this.OnPropertyChanged("dev_customer");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dev_description")]
		public string dev_description
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dev_description");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_description");
				this.SetAttributeValue("dev_description", value);
				this.OnPropertyChanged("dev_description");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dev_priority")]
		public virtual dev_Case_dev_priority? dev_priority
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((dev_Case_dev_priority?)(EntityOptionSetEnum.GetEnum(this, "dev_priority")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_priority");
				this.SetAttributeValue("dev_priority", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("dev_priority");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dev_title")]
		public string dev_title
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dev_title");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_title");
				this.SetAttributeValue("dev_title", value);
				this.OnPropertyChanged("dev_title");
			}
		}
		
		/// <summary>
		/// Numer sekwencyjny operacji importu, w wyniku której został utworzony ten rekord.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator użytkownika, który zmodyfikował rekord.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Data i godzina modyfikacji rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator użytkownika delegowanego, który zmodyfikował rekord.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Data i godzina migracji rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Identyfikator właściciela
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator jednostki biznesowej, która jest właścicielem rekordu
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator zespołu, który jest właścicielem rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator użytkownika, który jest właścicielem rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Stan elementu/elementów Case
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<customer_integration.Infrastructure.CRM.Models.dev_CaseState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((customer_integration.Infrastructure.CRM.Models.dev_CaseState)(System.Enum.ToObject(typeof(customer_integration.Infrastructure.CRM.Models.dev_CaseState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual dev_Case_StatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((dev_Case_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// Tylko do użytku wewnętrznego.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Kod strefy czasowej używanej podczas tworzenia rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Numer wersji
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 dev_Apartment_cases_dev_Case
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dev_cases")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dev_Apartment_cases_dev_Case")]
		public customer_integration.Infrastructure.CRM.Models.dev_Apartment dev_Apartment_cases_dev_Case
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<customer_integration.Infrastructure.CRM.Models.dev_Apartment>("dev_Apartment_cases_dev_Case", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_Apartment_cases_dev_Case");
				this.SetRelatedEntity<customer_integration.Infrastructure.CRM.Models.dev_Apartment>("dev_Apartment_cases_dev_Case", null, value);
				this.OnPropertyChanged("dev_Apartment_cases_dev_Case");
			}
		}
		
		/// <summary>
		/// N:1 dev_case_apartment_dev_apartment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dev_apartment")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dev_case_apartment_dev_apartment")]
		public customer_integration.Infrastructure.CRM.Models.dev_Apartment dev_case_apartment_dev_apartment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<customer_integration.Infrastructure.CRM.Models.dev_Apartment>("dev_case_apartment_dev_apartment", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_case_apartment_dev_apartment");
				this.SetRelatedEntity<customer_integration.Infrastructure.CRM.Models.dev_Apartment>("dev_case_apartment_dev_apartment", null, value);
				this.OnPropertyChanged("dev_case_apartment_dev_apartment");
			}
		}
		
		/// <summary>
		/// N:1 dev_case_customer_dev_customer
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dev_customer")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dev_case_customer_dev_customer")]
		public customer_integration.Infrastructure.CRM.Models.dev_Customer dev_case_customer_dev_customer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<customer_integration.Infrastructure.CRM.Models.dev_Customer>("dev_case_customer_dev_customer", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_case_customer_dev_customer");
				this.SetRelatedEntity<customer_integration.Infrastructure.CRM.Models.dev_Customer>("dev_case_customer_dev_customer", null, value);
				this.OnPropertyChanged("dev_case_customer_dev_customer");
			}
		}
		
		/// <summary>
		/// N:1 dev_Customer_case_dev_Case
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dev_case")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dev_Customer_case_dev_Case")]
		public customer_integration.Infrastructure.CRM.Models.dev_Customer dev_Customer_case_dev_Case
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<customer_integration.Infrastructure.CRM.Models.dev_Customer>("dev_Customer_case_dev_Case", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dev_Customer_case_dev_Case");
				this.SetRelatedEntity<customer_integration.Infrastructure.CRM.Models.dev_Customer>("dev_Customer_case_dev_Case", null, value);
				this.OnPropertyChanged("dev_Customer_case_dev_Case");
			}
		}
		
		/// <summary>
		/// N:1 lk_dev_case_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_dev_case_createdby")]
		public customer_integration.Infrastructure.CRM.Models.SystemUser lk_dev_case_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<customer_integration.Infrastructure.CRM.Models.SystemUser>("lk_dev_case_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_dev_case_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_dev_case_createdonbehalfby")]
		public customer_integration.Infrastructure.CRM.Models.SystemUser lk_dev_case_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<customer_integration.Infrastructure.CRM.Models.SystemUser>("lk_dev_case_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_dev_case_createdonbehalfby");
				this.SetRelatedEntity<customer_integration.Infrastructure.CRM.Models.SystemUser>("lk_dev_case_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_dev_case_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_dev_case_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_dev_case_modifiedby")]
		public customer_integration.Infrastructure.CRM.Models.SystemUser lk_dev_case_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<customer_integration.Infrastructure.CRM.Models.SystemUser>("lk_dev_case_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_dev_case_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_dev_case_modifiedonbehalfby")]
		public customer_integration.Infrastructure.CRM.Models.SystemUser lk_dev_case_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<customer_integration.Infrastructure.CRM.Models.SystemUser>("lk_dev_case_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_dev_case_modifiedonbehalfby");
				this.SetRelatedEntity<customer_integration.Infrastructure.CRM.Models.SystemUser>("lk_dev_case_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_dev_case_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 user_dev_case
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_dev_case")]
		public customer_integration.Infrastructure.CRM.Models.SystemUser user_dev_case
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<customer_integration.Infrastructure.CRM.Models.SystemUser>("user_dev_case", null);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public dev_Case(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["dev_caseid"] = base.Id;
                        break;
                    case "dev_caseid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}
