//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ServiceDeskPro_integration.Infrastructure.CRM.Models
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdp_escalationlogState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Records of case escalations between agents.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("sdp_escalationlog")]
	public partial class sdp_escalationlog : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string sdp_caseid = "sdp_caseid";
			public const string sdp_escalationdate = "sdp_escalationdate";
			public const string sdp_escalationlogId = "sdp_escalationlogid";
			public const string Id = "sdp_escalationlogid";
			public const string sdp_escalationname = "sdp_escalationname";
			public const string sdp_escalationreason = "sdp_escalationreason";
			public const string sdp_fromagentid = "sdp_fromagentid";
			public const string sdp_toagentid = "sdp_toagentid";
			public const string sdp_triggeredby = "sdp_triggeredby";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string lk_sdp_escalationlog_createdby = "lk_sdp_escalationlog_createdby";
			public const string lk_sdp_escalationlog_createdonbehalfby = "lk_sdp_escalationlog_createdonbehalfby";
			public const string lk_sdp_escalationlog_modifiedby = "lk_sdp_escalationlog_modifiedby";
			public const string lk_sdp_escalationlog_modifiedonbehalfby = "lk_sdp_escalationlog_modifiedonbehalfby";
			public const string sdp_escalationlog_caseid_sdp_case = "sdp_escalationlog_caseid_sdp_case";
			public const string sdp_escalationlog_fromagentid_sdp_agent = "sdp_escalationlog_fromagentid_sdp_agent";
			public const string sdp_escalationlog_toagentid_sdp_agent = "sdp_escalationlog_toagentid_sdp_agent";
			public const string user_sdp_escalationlog = "user_sdp_escalationlog";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public sdp_escalationlog() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "sdp_escalationlog";
		
		public const string EntitySchemaName = "sdp_escalationlog";
		
		public const string PrimaryIdAttribute = "sdp_escalationlogid";
		
		public const string PrimaryNameAttribute = "sdp_escalationname";
		
		public const string EntityLogicalCollectionName = "sdp_escalationlogs";
		
		public const string EntitySetName = "sdp_escalationlogs";
		
		public const int EntityTypeCode = 10701;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator użytkownika, który utworzył rekord.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Data i godzina utworzenia rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator użytkownika delegowanego, który utworzył rekord.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Numer sekwencyjny operacji importu, w wyniku której został utworzony ten rekord.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator użytkownika, który zmodyfikował rekord.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Data i godzina modyfikacji rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator użytkownika delegowanego, który zmodyfikował rekord.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Data i godzina migracji rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Identyfikator właściciela
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator jednostki biznesowej, która jest właścicielem rekordu
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator zespołu, który jest właścicielem rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator użytkownika, który jest właścicielem rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Identifier of the related case
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdp_caseid")]
		public Microsoft.Xrm.Sdk.EntityReference sdp_caseid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("sdp_caseid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_caseid");
				this.SetAttributeValue("sdp_caseid", value);
				this.OnPropertyChanged("sdp_caseid");
			}
		}
		
		/// <summary>
		/// Date and time when escalation occurred
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdp_escalationdate")]
		public string sdp_escalationdate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("sdp_escalationdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_escalationdate");
				this.SetAttributeValue("sdp_escalationdate", value);
				this.OnPropertyChanged("sdp_escalationdate");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator wystąpień encji
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdp_escalationlogid")]
		public System.Nullable<System.Guid> sdp_escalationlogId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("sdp_escalationlogid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_escalationlogId");
				this.SetAttributeValue("sdp_escalationlogid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("sdp_escalationlogId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdp_escalationlogid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.sdp_escalationlogId = value;
			}
		}
		
		/// <summary>
		/// Primary key name of the escalation log
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdp_escalationname")]
		public string sdp_escalationname
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("sdp_escalationname");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_escalationname");
				this.SetAttributeValue("sdp_escalationname", value);
				this.OnPropertyChanged("sdp_escalationname");
			}
		}
		
		/// <summary>
		/// Reason for escalation
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdp_escalationreason")]
		public string sdp_escalationreason
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("sdp_escalationreason");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_escalationreason");
				this.SetAttributeValue("sdp_escalationreason", value);
				this.OnPropertyChanged("sdp_escalationreason");
			}
		}
		
		/// <summary>
		/// Agent ID from whom the case was escalated
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdp_fromagentid")]
		public Microsoft.Xrm.Sdk.EntityReference sdp_fromagentid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("sdp_fromagentid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_fromagentid");
				this.SetAttributeValue("sdp_fromagentid", value);
				this.OnPropertyChanged("sdp_fromagentid");
			}
		}
		
		/// <summary>
		/// Agent ID to whom the case was escalated
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdp_toagentid")]
		public Microsoft.Xrm.Sdk.EntityReference sdp_toagentid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("sdp_toagentid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_toagentid");
				this.SetAttributeValue("sdp_toagentid", value);
				this.OnPropertyChanged("sdp_toagentid");
			}
		}
		
		/// <summary>
		/// User who triggered the escalation
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdp_triggeredby")]
		public string sdp_triggeredby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("sdp_triggeredby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_triggeredby");
				this.SetAttributeValue("sdp_triggeredby", value);
				this.OnPropertyChanged("sdp_triggeredby");
			}
		}
		
		/// <summary>
		/// Stan elementu/elementów Escalation Log
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_escalationlogState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_escalationlogState)(System.Enum.ToObject(typeof(ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_escalationlogState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Przyczyna stanu elementu/elementów Escalation Log
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual sdp_escalationlog_StatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((sdp_escalationlog_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// Tylko do użytku wewnętrznego.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Kod strefy czasowej używanej podczas tworzenia rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Numer wersji
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 lk_sdp_escalationlog_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_sdp_escalationlog_createdby")]
		public ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser lk_sdp_escalationlog_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser>("lk_sdp_escalationlog_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_sdp_escalationlog_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_sdp_escalationlog_createdonbehalfby")]
		public ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser lk_sdp_escalationlog_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser>("lk_sdp_escalationlog_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_sdp_escalationlog_createdonbehalfby");
				this.SetRelatedEntity<ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser>("lk_sdp_escalationlog_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_sdp_escalationlog_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_sdp_escalationlog_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_sdp_escalationlog_modifiedby")]
		public ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser lk_sdp_escalationlog_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser>("lk_sdp_escalationlog_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_sdp_escalationlog_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_sdp_escalationlog_modifiedonbehalfby")]
		public ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser lk_sdp_escalationlog_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser>("lk_sdp_escalationlog_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_sdp_escalationlog_modifiedonbehalfby");
				this.SetRelatedEntity<ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser>("lk_sdp_escalationlog_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_sdp_escalationlog_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 sdp_escalationlog_caseid_sdp_case
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdp_caseid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sdp_escalationlog_caseid_sdp_case")]
		public ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_case sdp_escalationlog_caseid_sdp_case
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_case>("sdp_escalationlog_caseid_sdp_case", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_escalationlog_caseid_sdp_case");
				this.SetRelatedEntity<ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_case>("sdp_escalationlog_caseid_sdp_case", null, value);
				this.OnPropertyChanged("sdp_escalationlog_caseid_sdp_case");
			}
		}
		
		/// <summary>
		/// N:1 sdp_escalationlog_fromagentid_sdp_agent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdp_fromagentid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sdp_escalationlog_fromagentid_sdp_agent")]
		public ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_agent sdp_escalationlog_fromagentid_sdp_agent
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_agent>("sdp_escalationlog_fromagentid_sdp_agent", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_escalationlog_fromagentid_sdp_agent");
				this.SetRelatedEntity<ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_agent>("sdp_escalationlog_fromagentid_sdp_agent", null, value);
				this.OnPropertyChanged("sdp_escalationlog_fromagentid_sdp_agent");
			}
		}
		
		/// <summary>
		/// N:1 sdp_escalationlog_toagentid_sdp_agent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdp_toagentid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sdp_escalationlog_toagentid_sdp_agent")]
		public ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_agent sdp_escalationlog_toagentid_sdp_agent
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_agent>("sdp_escalationlog_toagentid_sdp_agent", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_escalationlog_toagentid_sdp_agent");
				this.SetRelatedEntity<ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_agent>("sdp_escalationlog_toagentid_sdp_agent", null, value);
				this.OnPropertyChanged("sdp_escalationlog_toagentid_sdp_agent");
			}
		}
		
		/// <summary>
		/// N:1 user_sdp_escalationlog
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_sdp_escalationlog")]
		public ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser user_sdp_escalationlog
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser>("user_sdp_escalationlog", null);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public sdp_escalationlog(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["sdp_escalationlogid"] = base.Id;
                        break;
                    case "sdp_escalationlogid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}