//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ServiceDeskPro_integration.Infrastructure.CRM.Models
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sdp_agentState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Table containing agent details including contact and skill information.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("sdp_agent")]
	public partial class sdp_agent : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string sdp_agentId = "sdp_agentid";
			public const string Id = "sdp_agentid";
			public const string sdp_agentname = "sdp_agentname";
			public const string sdp_emailaddress = "sdp_emailaddress";
			public const string sdp_maximumopencases = "sdp_maximumopencases";
			public const string sdp_skilltier = "sdp_skilltier";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string lk_sdp_agent_createdby = "lk_sdp_agent_createdby";
			public const string lk_sdp_agent_createdonbehalfby = "lk_sdp_agent_createdonbehalfby";
			public const string lk_sdp_agent_modifiedby = "lk_sdp_agent_modifiedby";
			public const string lk_sdp_agent_modifiedonbehalfby = "lk_sdp_agent_modifiedonbehalfby";
			public const string user_sdp_agent = "user_sdp_agent";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public sdp_agent() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "sdp_agent";
		
		public const string EntitySchemaName = "sdp_agent";
		
		public const string PrimaryIdAttribute = "sdp_agentid";
		
		public const string PrimaryNameAttribute = "sdp_agentname";
		
		public const string EntityLogicalCollectionName = "sdp_agents";
		
		public const string EntitySetName = "sdp_agents";
		
		public const int EntityTypeCode = 10700;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator użytkownika, który utworzył rekord.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Data i godzina utworzenia rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator użytkownika delegowanego, który utworzył rekord.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Numer sekwencyjny operacji importu, w wyniku której został utworzony ten rekord.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator użytkownika, który zmodyfikował rekord.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Data i godzina modyfikacji rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator użytkownika delegowanego, który zmodyfikował rekord.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Data i godzina migracji rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Identyfikator właściciela
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator jednostki biznesowej, która jest właścicielem rekordu
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator zespołu, który jest właścicielem rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator użytkownika, który jest właścicielem rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Unikatowy identyfikator wystąpień encji
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdp_agentid")]
		public System.Nullable<System.Guid> sdp_agentId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("sdp_agentid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_agentId");
				this.SetAttributeValue("sdp_agentid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("sdp_agentId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdp_agentid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.sdp_agentId = value;
			}
		}
		
		/// <summary>
		/// Primary key: Name of the agent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdp_agentname")]
		public string sdp_agentname
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("sdp_agentname");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_agentname");
				this.SetAttributeValue("sdp_agentname", value);
				this.OnPropertyChanged("sdp_agentname");
			}
		}
		
		/// <summary>
		/// Email address of the agent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdp_emailaddress")]
		public string sdp_emailaddress
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("sdp_emailaddress");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_emailaddress");
				this.SetAttributeValue("sdp_emailaddress", value);
				this.OnPropertyChanged("sdp_emailaddress");
			}
		}
		
		/// <summary>
		/// Maximum number of open cases the agent can handle
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdp_maximumopencases")]
		public string sdp_maximumopencases
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("sdp_maximumopencases");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_maximumopencases");
				this.SetAttributeValue("sdp_maximumopencases", value);
				this.OnPropertyChanged("sdp_maximumopencases");
			}
		}
		
		/// <summary>
		/// Skill tier level of the agent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sdp_skilltier")]
		public virtual sdp_agent_sdp_skilltier? sdp_skilltier
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((sdp_agent_sdp_skilltier?)(EntityOptionSetEnum.GetEnum(this, "sdp_skilltier")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_skilltier");
				this.SetAttributeValue("sdp_skilltier", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("sdp_skilltier");
			}
		}
		
		/// <summary>
		/// Stan elementu/elementów Agent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_agentState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_agentState)(System.Enum.ToObject(typeof(ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_agentState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Przyczyna stanu elementu/elementów Agent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual sdp_agent_StatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((sdp_agent_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// Tylko do użytku wewnętrznego.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Kod strefy czasowej używanej podczas tworzenia rekordu.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Numer wersji
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N sdp_agent_ActivityParties
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sdp_agent_ActivityParties")]
		public System.Collections.Generic.IEnumerable<ServiceDeskPro_integration.Infrastructure.CRM.Models.ActivityParty> sdp_agent_ActivityParties
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<ServiceDeskPro_integration.Infrastructure.CRM.Models.ActivityParty>("sdp_agent_ActivityParties", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_agent_ActivityParties");
				this.SetRelatedEntities<ServiceDeskPro_integration.Infrastructure.CRM.Models.ActivityParty>("sdp_agent_ActivityParties", null, value);
				this.OnPropertyChanged("sdp_agent_ActivityParties");
			}
		}
		
		/// <summary>
		/// 1:N sdp_agent_ActivityPointers
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sdp_agent_ActivityPointers")]
		public System.Collections.Generic.IEnumerable<ServiceDeskPro_integration.Infrastructure.CRM.Models.ActivityPointer> sdp_agent_ActivityPointers
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<ServiceDeskPro_integration.Infrastructure.CRM.Models.ActivityPointer>("sdp_agent_ActivityPointers", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_agent_ActivityPointers");
				this.SetRelatedEntities<ServiceDeskPro_integration.Infrastructure.CRM.Models.ActivityPointer>("sdp_agent_ActivityPointers", null, value);
				this.OnPropertyChanged("sdp_agent_ActivityPointers");
			}
		}
		
		/// <summary>
		/// 1:N sdp_agent_Emails
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sdp_agent_Emails")]
		public System.Collections.Generic.IEnumerable<ServiceDeskPro_integration.Infrastructure.CRM.Models.Email> sdp_agent_Emails
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<ServiceDeskPro_integration.Infrastructure.CRM.Models.Email>("sdp_agent_Emails", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_agent_Emails");
				this.SetRelatedEntities<ServiceDeskPro_integration.Infrastructure.CRM.Models.Email>("sdp_agent_Emails", null, value);
				this.OnPropertyChanged("sdp_agent_Emails");
			}
		}
		
		/// <summary>
		/// 1:N sdp_case_assignedagentid_sdp_agent
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sdp_case_assignedagentid_sdp_agent")]
		public System.Collections.Generic.IEnumerable<ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_case> sdp_case_assignedagentid_sdp_agent
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_case>("sdp_case_assignedagentid_sdp_agent", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_case_assignedagentid_sdp_agent");
				this.SetRelatedEntities<ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_case>("sdp_case_assignedagentid_sdp_agent", null, value);
				this.OnPropertyChanged("sdp_case_assignedagentid_sdp_agent");
			}
		}
		
		/// <summary>
		/// 1:N sdp_case2_assignedagentid_sdp_agent
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sdp_case2_assignedagentid_sdp_agent")]
		public System.Collections.Generic.IEnumerable<ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_case2> sdp_case2_assignedagentid_sdp_agent
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_case2>("sdp_case2_assignedagentid_sdp_agent", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_case2_assignedagentid_sdp_agent");
				this.SetRelatedEntities<ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_case2>("sdp_case2_assignedagentid_sdp_agent", null, value);
				this.OnPropertyChanged("sdp_case2_assignedagentid_sdp_agent");
			}
		}
		
		/// <summary>
		/// 1:N sdp_escalationlog_fromagentid_sdp_agent
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sdp_escalationlog_fromagentid_sdp_agent")]
		public System.Collections.Generic.IEnumerable<ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_escalationlog> sdp_escalationlog_fromagentid_sdp_agent
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_escalationlog>("sdp_escalationlog_fromagentid_sdp_agent", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_escalationlog_fromagentid_sdp_agent");
				this.SetRelatedEntities<ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_escalationlog>("sdp_escalationlog_fromagentid_sdp_agent", null, value);
				this.OnPropertyChanged("sdp_escalationlog_fromagentid_sdp_agent");
			}
		}
		
		/// <summary>
		/// 1:N sdp_escalationlog_toagentid_sdp_agent
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sdp_escalationlog_toagentid_sdp_agent")]
		public System.Collections.Generic.IEnumerable<ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_escalationlog> sdp_escalationlog_toagentid_sdp_agent
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_escalationlog>("sdp_escalationlog_toagentid_sdp_agent", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sdp_escalationlog_toagentid_sdp_agent");
				this.SetRelatedEntities<ServiceDeskPro_integration.Infrastructure.CRM.Models.sdp_escalationlog>("sdp_escalationlog_toagentid_sdp_agent", null, value);
				this.OnPropertyChanged("sdp_escalationlog_toagentid_sdp_agent");
			}
		}
		
		/// <summary>
		/// N:1 lk_sdp_agent_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_sdp_agent_createdby")]
		public ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser lk_sdp_agent_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser>("lk_sdp_agent_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_sdp_agent_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_sdp_agent_createdonbehalfby")]
		public ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser lk_sdp_agent_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser>("lk_sdp_agent_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_sdp_agent_createdonbehalfby");
				this.SetRelatedEntity<ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser>("lk_sdp_agent_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_sdp_agent_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_sdp_agent_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_sdp_agent_modifiedby")]
		public ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser lk_sdp_agent_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser>("lk_sdp_agent_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_sdp_agent_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_sdp_agent_modifiedonbehalfby")]
		public ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser lk_sdp_agent_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser>("lk_sdp_agent_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_sdp_agent_modifiedonbehalfby");
				this.SetRelatedEntity<ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser>("lk_sdp_agent_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_sdp_agent_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 user_sdp_agent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_sdp_agent")]
		public ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser user_sdp_agent
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<ServiceDeskPro_integration.Infrastructure.CRM.Models.SystemUser>("user_sdp_agent", null);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public sdp_agent(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["sdp_agentid"] = base.Id;
                        break;
                    case "sdp_agentid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}